services:
  avito-merch-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Jwt__SecretKey=your_32_bytes_long_secret_key_for_jwt_authentication_256_bits_here
      - Jwt__Issuer=AvitoMerchShop
      - Jwt__Audience=AvitoUsers
      - ConnectionStrings__PostgreSQLConnection=Host=db;Port=5432;Database=avito_merch;Username=postgres;Password=qwerty
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty 
      POSTGRES_DB: avito_merch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d avito_merch"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge